DROP TABLE IF EXISTS OSM_stops;
CREATE TABLE OSM_stops
 ( id bigint NOT NULL PRIMARY KEY,
    lat float,
    lon float,
    type text,
    timestamp timestamp,
    version integer,
    username text,
    name text,
    name_De_Lijn text,
    name_TEC text,
    name_nl text,
    name_fr text,
    name_en text,
    name_de text,
    ref text,
    ref_De_Lijn text,
    ref_TECB text,
    ref_TECC text,
    ref_TECH text,
    ref_TECN text,
    ref_TECL text,
    ref_TECX text,
    route_ref text,
    route_ref_De_Lijn text,
    route_ref_TECB text,
    route_ref_TECC text,
    route_ref_TECH text,
    route_ref_TECN text,
    route_ref_TECL text,
    route_ref_TECX text,
    zone text,
    zone_De_Lijn text,
    zone_TEC text,
    source text,
    operator text)
  WITH ( OIDS=FALSE );
ALTER TABLE OSM_stops OWNER TO polyglot;

