# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lines', '0003_line_xml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='xml',
        ),
    ]
