# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 05:40
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('osm_id', models.TextField(help_text='composed of n, w, r + id in OSM', primary_key=True, serialize=False)),
                ('changed_in_osm', models.BooleanField()),
                ('changed_by_operator', models.BooleanField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text='Represented as (longitude, latitude)', srid=4326)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('name_de_lijn', models.TextField(blank=True, null=True)),
                ('name_tec', models.TextField(blank=True, null=True)),
                ('name_nl', models.TextField(blank=True, null=True)),
                ('name_fr', models.TextField(blank=True, null=True)),
                ('name_en', models.TextField(blank=True, null=True)),
                ('name_de', models.TextField(blank=True, null=True)),
                ('ref', models.TextField(blank=True, null=True)),
                ('ref_de_lijn', models.TextField(blank=True, null=True)),
                ('ref_tecb', models.TextField(blank=True, null=True)),
                ('ref_tecc', models.TextField(blank=True, null=True)),
                ('ref_tech', models.TextField(blank=True, null=True)),
                ('ref_tecn', models.TextField(blank=True, null=True)),
                ('ref_tecl', models.TextField(blank=True, null=True)),
                ('ref_tecx', models.TextField(blank=True, null=True)),
                ('route_ref', models.TextField(blank=True, null=True)),
                ('route_ref_de_lijn', models.TextField(blank=True, null=True)),
                ('route_ref_tecb', models.TextField(blank=True, null=True)),
                ('route_ref_tecc', models.TextField(blank=True, null=True)),
                ('route_ref_tech', models.TextField(blank=True, null=True)),
                ('route_ref_tecn', models.TextField(blank=True, null=True)),
                ('route_ref_tecl', models.TextField(blank=True, null=True)),
                ('route_ref_tecx', models.TextField(blank=True, null=True)),
                ('zone', models.TextField(blank=True, null=True)),
                ('zone_de_lijn', models.TextField(blank=True, null=True)),
                ('zone_tec', models.TextField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('operator', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StopFromOperator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text='Represented as (longitude, latitude)', srid=4326)),
                ('offset', models.FloatField(blank=True, null=True)),
                ('identifier', models.TextField(blank=True, null=True)),
                ('route_ref', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.Operator')),
                ('osmid', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='stops.Stop')),
            ],
        ),
    ]
