# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stopfromoperator',
            name='stopisaccessible',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='stop',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operators.Operator'),
        ),
    ]
