# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stops', '0003_auto_20170423_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='dummy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
